import type { ComponentContext } from "./types";
import { themeVars } from "./components";

/* ==========================================================================
   NEXORA — Generated site stylesheet
   One responsive, dependency-free stylesheet is emitted per site and themed
   with CSS custom properties. No build step, no external CSS runtime.
   ========================================================================== */

export function buildStylesheet(ctx: ComponentContext): string {
  return `/* Generated by NEXORA — ${ctx.business.name} */
${themeVars(ctx)}
*,*::before,*::after{box-sizing:border-box}
html{-webkit-text-size-adjust:100%;scroll-behavior:smooth}
body{margin:0;background:var(--nx-bg);color:var(--nx-text);font-family:var(--nx-font-b);
  font-size:16px;line-height:1.65;-webkit-font-smoothing:antialiased}
img{max-width:100%;height:auto;display:block}
a{color:inherit;text-decoration:none}
h1,h2,h3,h4{font-family:var(--nx-font-h);line-height:1.15;letter-spacing:-.02em;margin:0 0 .5em}
p{margin:0 0 1em}
:focus-visible{outline:3px solid var(--nx-accent);outline-offset:2px;border-radius:4px}
.tnum{font-variant-numeric:tabular-nums}
.nx-skip{position:absolute;left:-9999px;top:0;background:var(--nx-primary);color:#fff;padding:10px 16px;z-index:100}
.nx-skip:focus{left:8px;top:8px}

.nx-container{width:100%;max-width:1160px;margin:0 auto;padding:0 24px}
.nx-container--narrow{max-width:760px}
.nx-section{padding:clamp(48px,7vw,92px) 0}
.nx-section--alt{background:var(--nx-surface)}
.nx-eyebrow{font-size:.75rem;font-weight:700;letter-spacing:.14em;text-transform:uppercase;
  color:var(--nx-primary);margin:0 0 12px}
.nx-h2{font-size:clamp(1.6rem,3.4vw,2.5rem);margin:0 0 28px;max-width:22ch}
.nx-page-title{font-size:clamp(1.7rem,3.6vw,2.6rem);margin:0 0 24px;max-width:24ch}
.nx-lead{font-size:1.05rem;color:var(--nx-muted);max-width:56ch}
.nx-note{font-size:.85rem;color:var(--nx-muted)}
.nx-link{color:var(--nx-primary);font-weight:600;font-size:.9rem}

/* buttons */
.nx-btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;
  padding:11px 20px;border-radius:var(--nx-radius);border:1px solid transparent;
  font:inherit;font-weight:600;font-size:.92rem;cursor:pointer;transition:transform .16s ease,box-shadow .16s ease,background .16s ease}
.nx-btn:hover{transform:translateY(-1px)}
.nx-btn--primary{background:var(--nx-primary);color:#fff;box-shadow:0 8px 24px -10px var(--nx-primary)}
.nx-btn--primary:hover{background:var(--nx-primary-dark)}
.nx-btn--ghost{background:transparent;border-color:color-mix(in srgb,var(--nx-text) 22%,transparent);color:var(--nx-text)}
.nx-btn--ghost:hover{border-color:var(--nx-primary)}
.nx-btn--wa{background:#25d366;color:#04240f}
.nx-btn--lg{padding:15px 26px;font-size:1rem}
.nx-btn--sm{padding:8px 14px;font-size:.82rem}
.nx-badge{display:inline-block;background:var(--nx-accent);color:#04240f;font-size:.7rem;
  font-weight:700;padding:3px 9px;border-radius:999px;letter-spacing:.06em;text-transform:uppercase}

/* nav */
.nx-nav{position:sticky;top:0;z-index:50;display:flex;align-items:center;gap:20px;
  padding:14px 24px;background:color-mix(in srgb,var(--nx-bg) 88%,transparent);
  backdrop-filter:blur(12px);border-bottom:1px solid color-mix(in srgb,var(--nx-text) 10%,transparent)}
.nx-nav__brand{display:flex;align-items:center;gap:10px;font-family:var(--nx-font-h);font-weight:700;font-size:1.05rem}
.nx-nav__mark{width:32px;height:32px;border-radius:9px;background:linear-gradient(135deg,var(--nx-primary),var(--nx-accent));
  color:#fff;display:grid;place-items:center;font-size:.95rem}
.nx-nav__links{display:flex;gap:6px;margin-left:auto}
.nx-nav__link{padding:8px 13px;border-radius:var(--nx-radius);font-size:.9rem;font-weight:500;color:var(--nx-muted)}
.nx-nav__link:hover{color:var(--nx-text);background:color-mix(in srgb,var(--nx-text) 6%,transparent)}
.nx-nav__link[aria-current]{color:var(--nx-primary);background:color-mix(in srgb,var(--nx-primary) 12%,transparent)}
.nx-nav__toggle{display:none;flex-direction:column;gap:5px;background:none;border:0;padding:8px;cursor:pointer}
.nx-nav__toggle span{width:22px;height:2px;background:var(--nx-text);display:block;border-radius:2px}
.nx-mobile-menu{display:none;flex-direction:column;gap:4px;padding:12px 24px 20px;background:var(--nx-bg);
  border-bottom:1px solid color-mix(in srgb,var(--nx-text) 10%,transparent)}
.nx-mobile-menu a{padding:11px 4px;font-weight:600;border-bottom:1px solid color-mix(in srgb,var(--nx-text) 8%,transparent)}

/* hero */
.nx-hero{padding:clamp(48px,8vw,104px) 0 clamp(40px,6vw,80px);overflow:hidden}
.nx-hero__inner{display:grid;grid-template-columns:1.05fr .95fr;gap:48px;align-items:center;
  width:100%;max-width:1160px;margin:0 auto;padding:0 24px}
.nx-hero__title{font-size:clamp(2.1rem,5.4vw,3.7rem);margin:0 0 18px}
.nx-hero__sub{font-size:1.08rem;color:var(--nx-muted);max-width:46ch;margin-bottom:28px}
.nx-hero__actions{display:flex;flex-wrap:wrap;gap:12px}
.nx-hero__rating{display:flex;align-items:center;gap:10px;margin-top:22px;font-size:.9rem;color:var(--nx-muted)}
.nx-stars{color:#f59e0b;letter-spacing:2px}
.nx-hero__art{position:relative;min-height:340px}
.nx-hero__blob{position:absolute;inset:8% 4%;border-radius:42% 58% 54% 46%/48% 42% 58% 52%;
  background:linear-gradient(140deg,var(--nx-primary),var(--nx-accent));opacity:.22;filter:blur(6px);animation:nx-float 9s ease-in-out infinite}
.nx-hero__card{position:absolute;border-radius:var(--nx-radius-lg);background:var(--nx-surface);
  border:1px solid color-mix(in srgb,var(--nx-text) 10%,transparent);box-shadow:0 30px 60px -30px rgba(0,0,0,.35)}
.nx-hero__card--a{width:58%;height:56%;left:6%;top:12%;animation:nx-float 7s ease-in-out infinite}
.nx-hero__card--b{width:44%;height:40%;right:2%;bottom:8%;animation:nx-float 8.5s ease-in-out infinite reverse}
@keyframes nx-float{0%,100%{transform:translateY(0)}50%{transform:translateY(-14px)}}

/* grids + cards */
.nx-grid{display:grid;gap:20px}
.nx-grid--2{grid-template-columns:repeat(2,1fr)}
.nx-grid--3{grid-template-columns:repeat(3,1fr)}
.nx-grid--4{grid-template-columns:repeat(4,1fr)}
.nx-card{background:var(--nx-surface);border:1px solid color-mix(in srgb,var(--nx-text) 9%,transparent);
  border-radius:var(--nx-radius-lg);padding:26px;position:relative;transition:transform .18s ease,box-shadow .18s ease}
.nx-card:hover{transform:translateY(-4px);box-shadow:0 24px 48px -28px rgba(0,0,0,.4)}
.nx-card__index{font-size:.75rem;font-weight:700;color:var(--nx-primary);letter-spacing:.1em}
.nx-card__title{font-size:1.15rem;margin:10px 0 8px}
.nx-card__text{font-size:.93rem;color:var(--nx-muted);margin:0 0 14px}
.nx-card--price .nx-price{font-family:var(--nx-font-h);font-size:1.7rem;font-weight:700;margin:4px 0 10px}

.nx-feature{background:var(--nx-surface);border-radius:var(--nx-radius-lg);padding:22px;
  border:1px solid color-mix(in srgb,var(--nx-text) 9%,transparent)}
.nx-feature__icon{width:38px;height:38px;border-radius:11px;background:var(--nx-primary);color:#fff;
  display:grid;place-items:center;font-weight:700;margin-bottom:14px}
.nx-feature__title{font-size:1rem;margin:0}

/* stats */
.nx-stats{background:linear-gradient(120deg,var(--nx-primary-dark),var(--nx-primary));color:#fff;padding:44px 0}
.nx-stats__grid{display:grid;grid-template-columns:repeat(4,1fr);gap:20px;text-align:center}
.nx-stat__value{display:block;font-family:var(--nx-font-h);font-size:clamp(1.7rem,3.6vw,2.5rem);font-weight:700}
.nx-stat__label{font-size:.82rem;opacity:.85;letter-spacing:.05em;text-transform:uppercase}

/* quotes */
.nx-quote{margin:0;background:var(--nx-bg);border:1px solid color-mix(in srgb,var(--nx-text) 9%,transparent);
  border-radius:var(--nx-radius-lg);padding:26px}
.nx-quote blockquote{margin:0 0 16px;font-size:1rem;line-height:1.6}
.nx-quote figcaption{display:flex;flex-direction:column;font-size:.85rem;color:var(--nx-muted)}
.nx-quote--compact{padding:20px}

/* gallery */
.nx-gallery{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}
.nx-gallery__item{margin:0}
.nx-gallery__ph{aspect-ratio:4/3;border-radius:var(--nx-radius-lg);
  background:linear-gradient(140deg,hsl(var(--hue,240) 55% 62%),hsl(calc(var(--hue,240) + 40) 60% 48%));
  position:relative;overflow:hidden}
.nx-gallery__ph::after{content:"";position:absolute;inset:0;
  background:radial-gradient(120% 80% at 20% 10%,rgba(255,255,255,.28),transparent 60%)}
.nx-gallery__item figcaption{font-size:.85rem;color:var(--nx-muted);margin-top:8px}

/* menu list */
.nx-menu{margin-bottom:34px}
.nx-menu__section{font-size:1.25rem;margin-bottom:14px;color:var(--nx-primary)}
.nx-menu__list{list-style:none;margin:0;padding:0}
.nx-menu__list li{display:grid;grid-template-columns:auto 1fr auto;align-items:baseline;gap:10px;padding:9px 0;
  border-bottom:1px dashed color-mix(in srgb,var(--nx-text) 12%,transparent)}
.nx-menu__dots{border-bottom:1px dotted color-mix(in srgb,var(--nx-text) 25%,transparent);height:.7em}
.nx-menu__price{font-weight:700;font-variant-numeric:tabular-nums}
.nx-menu__desc{grid-column:1/-1;font-size:.85rem;color:var(--nx-muted)}

/* people */
.nx-person{text-align:center;background:var(--nx-surface);border-radius:var(--nx-radius-lg);padding:24px 18px;
  border:1px solid color-mix(in srgb,var(--nx-text) 9%,transparent)}
.nx-person__avatar{width:64px;height:64px;border-radius:50%;margin:0 auto 14px;
  background:linear-gradient(135deg,var(--nx-primary),var(--nx-accent));color:#fff;
  display:grid;place-items:center;font-family:var(--nx-font-h);font-size:1.4rem;font-weight:700}
.nx-person__name{font-size:1.02rem;margin:0 0 2px}
.nx-person__role{font-size:.82rem;color:var(--nx-primary);margin:0 0 8px;font-weight:600}
.nx-person__bio{font-size:.86rem;color:var(--nx-muted);margin:0}

/* timeline */
.nx-timeline{list-style:none;margin:0;padding:0;display:grid;gap:16px}
.nx-timeline__item{display:flex;gap:16px;align-items:flex-start}
.nx-timeline__num{flex:0 0 36px;height:36px;border-radius:50%;background:var(--nx-primary);color:#fff;
  display:grid;place-items:center;font-weight:700;font-size:.9rem}
.nx-timeline__item h3{font-size:1rem;margin:0 0 4px}
.nx-timeline__item p{margin:0;color:var(--nx-muted);font-size:.92rem}

/* faq */
.nx-faq{display:grid;gap:10px}
.nx-faq__item{background:var(--nx-surface);border:1px solid color-mix(in srgb,var(--nx-text) 9%,transparent);
  border-radius:var(--nx-radius);padding:16px 20px}
.nx-faq__item summary{cursor:pointer;font-weight:600;font-size:1rem;list-style:none}
.nx-faq__item summary::-webkit-details-marker{display:none}
.nx-faq__item summary::after{content:"+";float:right;color:var(--nx-primary);font-weight:700}
.nx-faq__item[open] summary::after{content:"–"}
.nx-faq__item p{margin:12px 0 0;color:var(--nx-muted);font-size:.93rem}

/* map */
.nx-map{display:grid;grid-template-columns:1.2fr .8fr;gap:28px;align-items:stretch}
.nx-map__frame{position:relative;min-height:300px;border-radius:var(--nx-radius-lg);overflow:hidden;
  background:
    linear-gradient(0deg,color-mix(in srgb,var(--nx-text) 8%,transparent) 1px,transparent 1px) 0 0/40px 40px,
    linear-gradient(90deg,color-mix(in srgb,var(--nx-text) 8%,transparent) 1px,transparent 1px) 0 0/40px 40px,
    var(--nx-surface)}
.nx-map__pin{position:absolute;left:50%;top:46%;width:20px;height:20px;border-radius:50%;
  background:var(--nx-primary);transform:translate(-50%,-50%);box-shadow:0 0 0 10px color-mix(in srgb,var(--nx-primary) 22%,transparent)}
.nx-map__label{position:absolute;left:50%;top:56%;transform:translateX(-50%);font-size:.8rem;font-weight:600;
  background:var(--nx-bg);padding:4px 10px;border-radius:999px;border:1px solid color-mix(in srgb,var(--nx-text) 12%,transparent)}
.nx-map__meta h3{font-size:.78rem;text-transform:uppercase;letter-spacing:.1em;color:var(--nx-muted);margin:16px 0 6px}
.nx-map__meta p{margin:0 0 10px}
.nx-hours{list-style:none;margin:0 0 18px;padding:0;font-size:.9rem;color:var(--nx-muted)}

/* forms */
.nx-form{display:grid;gap:16px;background:var(--nx-surface);padding:28px;border-radius:var(--nx-radius-lg);
  border:1px solid color-mix(in srgb,var(--nx-text) 9%,transparent)}
.nx-form--inline{grid-template-columns:repeat(2,1fr)}
.nx-form--inline .nx-btn{grid-column:1/-1}
.nx-field{display:grid;gap:6px}
.nx-field label{font-size:.8rem;font-weight:600;color:var(--nx-muted)}
.nx-field input,.nx-field select,.nx-field textarea{font:inherit;font-size:.95rem;padding:12px 14px;
  border-radius:var(--nx-radius);border:1px solid color-mix(in srgb,var(--nx-text) 16%,transparent);
  background:var(--nx-bg);color:var(--nx-text);width:100%}
.nx-field input:focus,.nx-field select:focus,.nx-field textarea:focus{outline:none;border-color:var(--nx-primary);
  box-shadow:0 0 0 3px color-mix(in srgb,var(--nx-primary) 18%,transparent)}
.nx-field input[aria-invalid="true"]{border-color:#ef4444}
.nx-form__status{margin:0;font-size:.86rem;color:var(--nx-muted);min-height:1.2em}
.nx-form__status[data-state="error"]{color:#ef4444}
.nx-form__status[data-state="ok"]{color:#059669}

.nx-contact{display:grid;grid-template-columns:1.1fr .9fr;gap:32px;align-items:start}
.nx-contact__aside h3{font-size:1rem;margin:0 0 14px}
.nx-contact__row{display:flex;justify-content:space-between;gap:12px;padding:12px 0;
  border-bottom:1px solid color-mix(in srgb,var(--nx-text) 10%,transparent);font-size:.92rem}
.nx-contact__row strong{color:var(--nx-muted);font-size:.78rem;text-transform:uppercase;letter-spacing:.08em}
.nx-contact__social{display:flex;flex-wrap:wrap;gap:8px;margin:18px 0}
.nx-social{font-size:.8rem;font-weight:600;padding:7px 12px;border-radius:999px;
  border:1px solid color-mix(in srgb,var(--nx-text) 16%,transparent)}

/* whatsapp band + cta */
.nx-wa{background:#075e54;color:#eafff6;padding:40px 0}
.nx-wa__inner{display:flex;align-items:center;justify-content:space-between;gap:24px;flex-wrap:wrap}
.nx-wa p{margin:6px 0 0;opacity:.85}
.nx-cta{background:linear-gradient(120deg,var(--nx-primary-dark),var(--nx-primary));color:#fff;padding:64px 0;text-align:center}
.nx-cta .nx-h2{color:#fff;margin-inline:auto}
.nx-cta p{max-width:52ch;margin:0 auto 24px;opacity:.9}
.nx-cta__actions{display:flex;gap:12px;justify-content:center;flex-wrap:wrap}
.nx-cta .nx-btn--ghost{border-color:rgba(255,255,255,.5);color:#fff}

/* products / work */
.nx-product{background:var(--nx-surface);border-radius:var(--nx-radius-lg);padding:18px;
  border:1px solid color-mix(in srgb,var(--nx-text) 9%,transparent);display:flex;flex-direction:column;gap:8px}
.nx-product__ph{aspect-ratio:1;border-radius:var(--nx-radius);
  background:linear-gradient(140deg,color-mix(in srgb,var(--nx-primary) 30%,var(--nx-surface)),var(--nx-surface))}
.nx-product__name{font-size:1rem;margin:0}
.nx-product__price{font-weight:700;margin:0;color:var(--nx-primary)}
.nx-product__desc{font-size:.85rem;color:var(--nx-muted);margin:0 0 6px}
.nx-work__ph{aspect-ratio:16/10;border-radius:var(--nx-radius-lg);margin-bottom:12px;
  background:linear-gradient(140deg,hsl(var(--hue,240) 52% 60%),hsl(calc(var(--hue,240) + 45) 55% 42%))}
.nx-work h3{font-size:1.02rem;margin:0 0 4px}
.nx-work p{margin:0;font-size:.87rem;color:var(--nx-muted)}

/* table */
.nx-table{border:1px solid color-mix(in srgb,var(--nx-text) 10%,transparent);border-radius:var(--nx-radius-lg);overflow:hidden}
.nx-table__head,.nx-table__row{display:grid;grid-template-columns:2.4fr 1fr 1fr auto;gap:16px;padding:14px 20px;align-items:center}
.nx-table__head{background:var(--nx-surface);font-size:.76rem;text-transform:uppercase;letter-spacing:.1em;color:var(--nx-muted)}
.nx-table__row{border-top:1px solid color-mix(in srgb,var(--nx-text) 8%,transparent);font-size:.92rem}
.nx-table__row small{color:var(--nx-muted)}

/* footer */
.nx-footer{background:var(--nx-neutral,#0f172a);color:#e2e8f0;padding:48px 0 24px}
.nx-footer__grid{display:grid;grid-template-columns:1.4fr 1fr 1fr;gap:28px;align-items:start}
.nx-footer__brand{font-family:var(--nx-font-h);font-weight:700;font-size:1.1rem;margin:0 0 8px}
.nx-footer nav{display:flex;flex-direction:column;gap:8px;font-size:.9rem}
.nx-footer nav a{opacity:.8}
.nx-footer nav a:hover{opacity:1;color:var(--nx-accent)}
.nx-footer__social{display:flex;flex-wrap:wrap;gap:10px;font-size:.85rem}
.nx-footer__legal{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;
  margin-top:32px;padding-top:20px;border-top:1px solid rgba(255,255,255,.12);font-size:.8rem;opacity:.75}
.nx-footer__demo{margin:0}

/* reveal animation */
.nx-reveal{opacity:0;transform:translateY(18px);transition:opacity .6s ease,transform .6s ease}
.nx-reveal.is-in{opacity:1;transform:none}
@media (prefers-reduced-motion: reduce){
  .nx-reveal{opacity:1;transform:none;transition:none}
  .nx-hero__blob,.nx-hero__card{animation:none}
  html{scroll-behavior:auto}
}

/* responsive */
@media (max-width: 960px){
  .nx-hero__inner{grid-template-columns:1fr}
  .nx-hero__art{min-height:240px;order:-1}
  .nx-grid--3,.nx-grid--4{grid-template-columns:repeat(2,1fr)}
  .nx-map{grid-template-columns:1fr}
  .nx-contact{grid-template-columns:1fr}
  .nx-stats__grid{grid-template-columns:repeat(2,1fr)}
}
@media (max-width: 640px){
  .nx-nav__links,.nx-nav__cta{display:none}
  .nx-nav__toggle{display:flex}
  .nx-mobile-menu{display:flex}
  .nx-grid--2,.nx-grid--3,.nx-grid--4{grid-template-columns:1fr}
  .nx-gallery{grid-template-columns:1fr}
  .nx-form--inline{grid-template-columns:1fr}
  .nx-table__head{display:none}
  .nx-table__row{grid-template-columns:1fr;gap:6px}
  .nx-footer__grid{grid-template-columns:1fr}
  .nx-section{padding:44px 0}
}
`;
}

/** Small progressive-enhancement script (mobile menu, reveal, form state). */
export function buildScript(): string {
  return `/* Generated by NEXORA */
(function () {
  "use strict";
  var toggle = document.querySelector(".nx-nav__toggle");
  var menu = document.getElementById("nx-mobile-menu");
  if (toggle && menu) {
    toggle.addEventListener("click", function () {
      var open = menu.hasAttribute("hidden");
      if (open) { menu.removeAttribute("hidden"); } else { menu.setAttribute("hidden", ""); }
      toggle.setAttribute("aria-expanded", String(open));
    });
  }

  var reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  var nodes = document.querySelectorAll(".nx-section, .nx-hero__copy");
  if (!reduce && "IntersectionObserver" in window) {
    nodes.forEach(function (n) { n.classList.add("nx-reveal"); });
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (e) { if (e.isIntersecting) { e.target.classList.add("is-in"); io.unobserve(e.target); } });
    }, { rootMargin: "0px 0px -8% 0px", threshold: 0.08 });
    nodes.forEach(function (n) { io.observe(n); });
  }

  document.querySelectorAll("form[data-nx-form]").forEach(function (form) {
    form.addEventListener("submit", function (ev) {
      ev.preventDefault();
      var status = form.querySelector(".nx-form__status");
      var required = form.querySelectorAll("[required]");
      var bad = false;
      required.forEach(function (f) {
        var ok = f.value.trim().length > 0;
        f.setAttribute("aria-invalid", ok ? "false" : "true");
        if (!ok) bad = true;
      });
      if (!status) return;
      if (bad) {
        status.dataset.state = "error";
        status.textContent = "Please complete the highlighted fields.";
        return;
      }
      status.dataset.state = "ok";
      status.textContent = "Thanks — this demo form is not connected to a live inbox yet. Connect the email integration to receive enquiries.";
    });
  });
})();
`;
}
